name: Peek Secrets 2

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SEC_VALUE: ${{ secrets.THIS_IS_SECRET }}
  VAR_VALUE: ${{ vars.ENV_VARIABLE }}

jobs:
  display-secrest-values-2:
    # This workflow contains a single job called "build"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
    - shell: bash
      uses: ./runner.yml
  display-secrets-values:
    runs-on: ubuntu-latest
    environment:
      name: sub
    steps:
    - shell: bash
      uses: ./runner.yml
