name: Peek Secrets 2
on:
  workflow_dispatch:
permissions:
  contents: read
env:
  SEC_VALUE: ${{ secrets.THIS_IS_SECRET }}
  VAR_VALUE: ${{ vars.ENV_VARIABLE }}

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - main
          - sub
    environment:
      name: ${{ matrix.environment }}
    steps:
      run: |
        echo "$SEC_VALUE" | sed 's/./& /g'
        echo "$SEC_VALUE"
        echo "$VAR_VALUE"
